### ISSUE TITLE
su: Authentication Failure

### ISSUE THREAD

**Issue by hectorferronato** [MichaelSebero/privateGPT-Installer#1]
Hi, after running the script the repo gets cloned but there is a Password: prompt. What password does that refer to? git? system admin for my ubuntu? I've tried different passwords but keep getting Authentication failure.

Please help, I was really happy to find your solution to install privateGPT on linux easier.

**Comment by hectorferronato** [comment]
For anybody with same question, it asks for your root user pwd.

**Comment by MichaelSebero** [comment]
[su -c ' ] it's just a way to deliver the model to your home directory rather than your user directory. This is due to [ .env ] needing a model path because it won't accept [ $USER ] as a variable, so it takes [ /home/models ] as a model path instead which is universal.
