### ISSUE TITLE
installer.sh needs to be run as root

### ISSUE THREAD

**Issue by jfpalomeque** [MichaelSebero/privateGPT-Installer#2]
I am using it in the wsl2, Ubuntu (Windows 10). It is needed to run as "sudo sh installer.sh", but some paths in "installer,sh" needs to be redone from $user to my real username.

Not sure if there is a better way of doing this, but looks like it is working in that way.

**Comment by MichaelSebero** [comment]
$USER is a shell variable which which automatically detects your username and uses it in the command.

**Comment by jfpalomeque** [comment]
As it needs to be run as root, user is root, but there are some issues when using ROOT as username.
