### ISSUE TITLE
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

### ISSUE THREAD

**Issue by jfpalomeque** [MichaelSebero/privateGPT-Installer#3]
I am having error "curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)"

**Comment by MichaelSebero** [comment]
GitHub was down that day for maintenance.

**Comment by jfpalomeque** [comment]
Error still appearing. Tried today, 28/5/2023, at 19:09 British time
